services:
  portfolio-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: portfolio-dev
    ports:
      - "6002:6002"
    volumes:
      - ./:/app
      - /app/node_modules/

  portfolio-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: portfolio-prod
    ports:
      - "6002:6002"
    environment:
      NODE_ENV: production
    restart: always